=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/presentation.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="element" type="elementType"/>
    <xs:complexType name="parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="elementType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="0"/>
            <xs:element type="referencesType" name="references" minOccurs="0"/>
            <xs:element type="parametersType" name="parameters" minOccurs="0"/>
            <xs:element type="xs:string" name="examples" minOccurs="0"/>
            <xs:element type="xs:string" name="notes" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="referenceComponentType" mixed="true">
        <xs:attribute type="xs:string" name="library" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element type="parameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="referencesType">
        <xs:sequence>
            <xs:element type="referenceComponentType" name="component" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="urlType" name="url" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="urlType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="link" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/PageLink.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        Generates a render request link to some other page in the application. If an activation context is supplied (as the context parameter), then the context values will be encoded into the\
        URL. If no context is supplied, then the target page itself will supply the context via a passivate event. Pages are not required to have an activation context. When a page does have an\
        activation context, the value typically represents the identity of some object displayed or otherwise manipulated by the page.
    </description>

    <parameters>
        <parameter name="anchor">
            An anchor value to append to the generated URL (the hash separator will be added automatically).
        </parameter>
        <parameter name="context">
            If provided, this is the activation context for the target page (the information will be encoded into the URL). If not provided, then the target page will provide its own activation\
            context.
        </parameter>
        <parameter name="disabled">
            If true, then then no link element is rendered (and no informal parameters as well). The body is, however, still rendered.
        </parameter>
        <parameter name="page">
            The logical name of the page to link to.
        </parameter>
    </parameters>

    <examples>
        <![CDATA[
<p>
    This will be a set of examples about PageLink.
</p>
	]]>
    </examples>

    <notes>
        <![CDATA[
<p>
    This will be more notes about PageLink.
</p>
	]]>
    </notes>
</element>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/test/resources/documentation/presentation/Complete.xml
<?xml version="1.0"?>

<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>Component that triggers an action on the server with a subsequent full page refresh.</description>

    <references>
        <component name="form/MyForm"/>
        <component library="core" name="ActionLink"/>

        <url name="Home page" link="http://www.mycomponentpage.com"/>
        <url name="Issue Tracker" link="http://www.mycomponentissuetracker.com"/>
    </references>

    <parameters>
        <parameter name="context">value1</parameter>

        <parameter name="disabled">value2</parameter>
    </parameters>

    <examples>Some component examples in HTML.</examples>

    <notes>Some component notes in HTML.</notes>
</component>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/BeanEditor.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        A component that generates a user interface for editing the properties of a bean. This is the central component of the org.apache.tapestry.corelib.components.BeanEditForm, and utilizes a\
        org.apache.tapestry.corelib.components.PropertyEditor for much of its functionality.
    </description>

    <parameters>
        <parameter name="model">
            The model that identifies the parameters to be edited, their order, and every other aspect. If not specified, a default bean model will be created from the type of the object bound to\
            the object parameter.
        </parameter>
        <parameter name="object">
            The object to be edited by the BeanEditor. This will be read when the component renders and updated when the form for the component is submitted. Typically, the container will listen\
            for a "prepare" event, in order to ensure that a non-null value is ready to be read or updated.
        </parameter>
        <parameter name="overrides">
            Where to search for local overrides of property editing blocks as block parameters. Further, the container of the overrides is used as the source for overridden validation\
            messages. This is normally the component itself, but when the component is used within a BeanEditForm, it will be the BeanEditForm's block parameter that will be searched.
        </parameter>
        <parameter name="remove">
            A comma-separated list of property names to be removed from the org.apache.tapestry.beaneditor.BeanModel. The names are case-insensitive.
        </parameter>
        <parameter name="reorder">
            A comma-separated list of property names indicating the order in which the properties should be presented. The names are case insensitive. Any properties not indicated in the list\
            will be appended to the end of the display order.
        </parameter>
    </parameters>
</element>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/DateField.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        A component used to collect a provided date from the user. This is a wrapper around the LGPL dynarch.com DHTML/JavaScript Calendar.
    </description>

    <parameters>
        <parameter name="clientId">
            The id used to generate a page-unique client-side identifier for the component. If a component renders multiple times, a suffix will be appended to the to id to ensure uniqueness.\
            The uniqued value may be accessed via the clientId property.
        </parameter>
        <parameter name="disabled">
            If true, then the field will render out with a disabled attribute (to turn off client-side behavior). Further, a disabled field ignores any value in the request when the form\
            is submitted.
        </parameter>
        <parameter name="editTime">
            If true, then the client-side calendar will show the time as well as the date. You will probably need to bind the format parameter as well when this is true, say to %m/%d/%y %H:%M.
        </parameter>
        <parameter name="label">
            The user presentable label for the field. If not provided, a reasonable label is generated from the component's id, first by looking for a message key named "id-label" (substituting\
            the component's actual id), then by converting the actual id to a presentable string (for example, "userId" to "User Id").
        </parameter>
        <parameter name="validate">
            The object that will perform input validation (which occurs after translation). The translate binding prefix is generally used to provide this object in a declarative fashion.
        </parameter>
        <parameter name="value">
            The value parameter of a DateField must be a java.util.Date.
        </parameter>
    </parameters>
</element>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/Palette.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        Multiple selection component. Generates a UI consisting of two select elements configured for multiple selection; the one on the left is the list of "available" elements, the one on the\
        right is "selected". Elements can be moved between the lists by clicking a button, or double clicking an option (and eventually, via drag and drop). The items in the available list are kept\
        ordered as per org.apache.tapestry.SelectModel order. When items are moved from the selected list to the available list, they items are inserted back into their proper positions. The Palette\
        may operate in normal or re-orderable mode, controlled by the reorder parameter. In normal mode, the items in the selected list are kept in the same "natural" order as the items in the\
        available list. In re-order mode, items moved to the selected list are simply added to the bottom of the list. In addition, two extra buttons appear to move items up and down within the\
        selected list. Much of the look and feel is driven by CSS, the default Tapestry CSS is used to set up the columns, etc. By default, the select element's widths are driven by the length of the\
        longest option, and it is common to override this to a fixed value: style DIV.t-palette SELECT { width: 300px; } /style This ensures that the two columns are the same width, and that the\
        column widths don't change as items move back and forth. Option groups within the org.apache.tapestry.SelectModel will be rendered, but are not supported by the many browsers, and are not\
        fully handled on the client side.
    </description>

    <parameters>
        <parameter name="clientId">
            The id used to generate a page-unique client-side identifier for the component. If a component renders multiple times, a suffix will be appended to the to id to ensure uniqueness.\
            The uniqued value may be accessed via the clientId property.
        </parameter>
        <parameter name="deselect">
            The image to use for the deselect button (the default is a left pointing arrow).
        </parameter>
        <parameter name="disabled">
            If true, then the field will render out with a disabled attribute (to turn off client-side behavior). Further, a disabled field ignores any value in the request when the form is\
            submitted.
        </parameter>
        <parameter name="encoder">
            Encoder used to translate between server-side objects and client-side strings.
        </parameter>
        <parameter name="label">
            The user presentable label for the field. If not provided, a reasonable label is generated from the component's id, first by looking for a message key named "id-label"\
            (substituting the component's actual id), then by converting the actual id to a presentable string (for example, "userId" to "User Id").
        </parameter>
        <parameter name="model">
            Model used to define the values and labels used when rendering.
        </parameter>
        <parameter name="moveDown">
            The image to use for the move down button (the default is a downward pointing arrow).
        </parameter>
        <parameter name="moveUp">
            The image to use for the move up button (the default is an upward pointing arrow).
        </parameter>
        <parameter name="reorder">
            If true, then additional buttons are provided on the client-side to allow for re-ordering of the values.
        </parameter>
        <parameter name="select">
            The image to use for the select button (the default is a right pointing arrow).
        </parameter>
        <parameter name="selected">
            The list of selected values from the org.apache.tapestry.SelectModel. This will be updated when the form is submitted. If the value for the parameter is null, a new list will be\
            created, otherwise the existing list will be cleared. If unbound, defaults to a property of the container matching this component's id.
        </parameter>
        <parameter name="size">
            Number of rows to display.
        </parameter>
    </parameters>
</element>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/GridRows.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        Renders out a series of rows within the table. Inside a org.apache.tapestry.corelib.components.Form, a series of row index numbers are stored into the form ( ). This is not ideal ... in a\
        situation where the data set can shift between the form render and the form submission, this can cause unexpected results, including applying changes to the wrong objects.
    </description>

    <parameters>
        <parameter name="currentPage">
            The current page number within the available pages (indexed from 1).
        </parameter>
        <parameter name="lean">
            If true, then the CSS class on each TD cell will be omitted, which can reduce the amount of output from the component overall by a considerable amount. Leave this as false, the\
            default, when you are leveraging the CSS to customize the look and feel of particular columns.
        </parameter>
        <parameter name="provider">
            Object that provides access to the bean and data models used to render the Grid.
        </parameter>
        <parameter name="row">
            The current row being rendered, this is primarily an output parameter used to allow the Grid, and the Grid's container, to know what object is being rendered.
        </parameter>
        <parameter name="rowClass">
            Parameter used to set the CSS class for each row (each tr element) within the tbody). This is not cached, so it will be recomputed for each row.
        </parameter>
        <parameter name="rowsPerPage">
            Number of rows displayed on each page. Long result sets are split across multiple pages.
        </parameter>
        <parameter name="sortAscending">
            If true, then the sort is ascending (A - Z), if false the descending (Z - A).
        </parameter>
        <parameter name="sortColumnId">
            The column which is currently being sorted. This value is the column's id, not its name. This parameter may be null, in which case no column is being used for sorting.
        </parameter>
        <parameter name="volatile">
            If true and the Loop is enclosed by a Form, then the normal state saving logic is turned off. Defaults to false, enabling state saving logic within Forms.
        </parameter>
    </parameters>
</element>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/PasswordField.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        A version of org.apache.tapestry.corelib.components.TextField, but rendered out as an input type="password" element. Further, the output value for a PasswordField is always blank.
    </description>

    <parameters>
        <parameter name="clientId">
            The id used to generate a page-unique client-side identifier for the component. If a component renders multiple times, a suffix will be appended to the to id to ensure uniqueness.\
            The uniqued value may be accessed via the clientId property.
        </parameter>
        <parameter name="disabled">
            If true, then the field will render out with a disabled attribute (to turn off client-side behavior). Further, a disabled field ignores any value in the request when the form is\
            submitted.
        </parameter>
        <parameter name="label">
            The user presentable label for the field. If not provided, a reasonable label is generated from the component's id, first by looking for a message key named "id-label" \
            (substituting the component's actual id), then by converting the actual id to a presentable string (for example, "userId" to "User Id").
        </parameter>
        <parameter name="nulls">
            Defines how nulls on the server side, or sent from the client side, are treated. The selected strategy may replace the nulls with some other value. The default strategy leaves nulls\
            alone. Another built-in strategy, zero, replaces nulls with the value 0.
        </parameter>
        <parameter name="translate">
            The object which will perform translation between server-side and client-side representations. If not specified, a value will usually be generated based on the type of the value\
            parameter.
        </parameter>
        <parameter name="validate">
            The object that will perform input validation (which occurs after translation). The translate binding prefix is generally used to provide this object in a declarative fashion.
        </parameter>
        <parameter name="value">
            The value to be read and updated. This is not necessarily a string, a translator may be provided to convert between client side and server side representations. If not bound, a\
            default binding is made to a property of the container matching the component's id. If no such property exists, then you will see a runtime exception due to the unbound value parameter.
        </parameter>
    </parameters>
</element>
